// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HandbookApi.Migrations
{
    [DbContext(typeof(Digital_Handbook_PortalContext))]
    [Migration("20261002130245_synctablesandmodels")]
    partial class synctablesandmodels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Digital_Handbook_Portal.Models.BragBook", b =>
                {
                    b.Property<int>("bragId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("bragId"));

                    b.Property<string>("content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("datePosted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("imageUrl")
                        .HasColumnType("text");

                    b.Property<string>("recipientName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("senderType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("bragId");

                    b.ToTable("BragBook");
                });

            modelBuilder.Entity("Digital_Handbook_Portal.Models.Community", b =>
                {
                    b.Property<int>("eventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("eventId"));

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("eventCategory")
                        .HasColumnType("integer");

                    b.Property<DateTime>("eventDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("location")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("eventId");

                    b.ToTable("Community");
                });

            modelBuilder.Entity("Digital_Handbook_Portal.Models.Doctor", b =>
                {
                    b.Property<int>("doctorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("doctorId"));

                    b.Property<string>("doctorImg")
                        .HasColumnType("text");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("fName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("lName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("suiteNumber")
                        .HasColumnType("integer");

                    b.HasKey("doctorId");

                    b.ToTable("Doctor");
                });

            modelBuilder.Entity("Digital_Handbook_Portal.Models.Policy", b =>
                {
                    b.Property<int>("policyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("policyId"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("categoryId")
                        .HasColumnType("integer");

                    b.Property<string>("contentSummary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("fileUrl")
                        .HasColumnType("text");

                    b.Property<string>("specificCategory")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("policyId");

                    b.HasIndex("categoryId");

                    b.ToTable("Policy");
                });

            modelBuilder.Entity("Digital_Handbook_Portal.Models.PolicyCategory", b =>
                {
                    b.Property<int>("categoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("categoryId"));

                    b.Property<string>("categoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("subCategory")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("categoryId");

                    b.ToTable("PolicyCategory");
                });

            modelBuilder.Entity("Digital_Handbook_Portal.Models.Quiz", b =>
                {
                    b.Property<int>("quizId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("quizId"));

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("estimateTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("passingScore")
                        .HasColumnType("integer");

                    b.Property<int>("score")
                        .HasColumnType("integer");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("totalQuestions")
                        .HasColumnType("integer");

                    b.HasKey("quizId");

                    b.ToTable("Quiz");
                });

            modelBuilder.Entity("Digital_Handbook_Portal.Models.QuizOption", b =>
                {
                    b.Property<int>("optionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("optionId"));

                    b.Property<bool>("isCorrect")
                        .HasColumnType("boolean");

                    b.Property<string>("optionText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("questionId")
                        .HasColumnType("integer");

                    b.HasKey("optionId");

                    b.HasIndex("questionId");

                    b.ToTable("QuizOption");
                });

            modelBuilder.Entity("Digital_Handbook_Portal.Models.QuizQuestion", b =>
                {
                    b.Property<int>("questionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("questionId"));

                    b.Property<string>("questionText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("quizId")
                        .HasColumnType("integer");

                    b.HasKey("questionId");

                    b.HasIndex("quizId");

                    b.ToTable("QuizQuestion");
                });

            modelBuilder.Entity("Digital_Handbook_Portal.Models.Resource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BreadcrumbPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ResourceUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.ToTable("Resource");
                });

            modelBuilder.Entity("Digital_Handbook_Portal.Models.User", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("userId"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("userId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Digital_Handbook_Portal.Models.Policy", b =>
                {
                    b.HasOne("Digital_Handbook_Portal.Models.PolicyCategory", "Category")
                        .WithMany("Policies")
                        .HasForeignKey("categoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Digital_Handbook_Portal.Models.QuizOption", b =>
                {
                    b.HasOne("Digital_Handbook_Portal.Models.QuizQuestion", "question")
                        .WithMany("options")
                        .HasForeignKey("questionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("question");
                });

            modelBuilder.Entity("Digital_Handbook_Portal.Models.QuizQuestion", b =>
                {
                    b.HasOne("Digital_Handbook_Portal.Models.Quiz", "quiz")
                        .WithMany("questions")
                        .HasForeignKey("quizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("quiz");
                });

            modelBuilder.Entity("Digital_Handbook_Portal.Models.PolicyCategory", b =>
                {
                    b.Navigation("Policies");
                });

            modelBuilder.Entity("Digital_Handbook_Portal.Models.Quiz", b =>
                {
                    b.Navigation("questions");
                });

            modelBuilder.Entity("Digital_Handbook_Portal.Models.QuizQuestion", b =>
                {
                    b.Navigation("options");
                });
#pragma warning restore 612, 618
        }
    }
}
